### ISSUE TITLE
Admin menu and controller sections

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-anonymous_codes#2]
ATS1 - Admin section for managing access codes

Adds a new section into the admin menu to manage two new tables in the database:1. Access code groups2. Tokens for the groupThis task, setups the menu, migrations and the initial CRUD for generating the groups and the tokens (screenshots provided)

Initial: 
![imatge](https://github.com/openpoke/decidim/assets/40388743/9b857e68-51d2-457b-b7b0-d2217087b528)

Final:
![imatge](https://github.com/openpoke/decidim/assets/40388743/7ab10e81-9cd9-4da4-a854-687fa17511b3)

**Tasks**
- [x] Create global admin menu section (register a menu)
- [x] Create controller and routes for the new section "Access codes groups"
- [x] Create new table migration with the `codes_groups` table. Fields: via #8 
  - [x] Title (multilang)
  - [x] Expiration date (timestamp)
  - [x] Active (boolean)
  - [x] Re-use max (integer)
  - [x] Resource (polymorphic relation of type `has_one`). This will relate to a survey initially only.
- [ ]  CRUD operations on the table/controllers/views. Use forms/commands as per Decidim standards
- [ ] Tests
