### ISSUE TITLE
Hack the survey's admin component config 

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-anonymous_codes#5]
Hack the survey's admin component config 

Adds into the survey's component configuration an option where to choose if that survey can be answered using access tokens (screenshot provided)

![imatge](https://github.com/openpoke/decidim/assets/40388743/b63983e4-0964-403a-8a72-8da34c8f6d64)

**Tasks**
- [ ] ~Through an initializer, add the option "Require an access code to answer". Linked with a "select" to on of the tokens groups available.~
- [ ] ~On saving/destroying the component (use ComponentManifest hooks: `on(:create)`, `on(:update)`, `on(:destroy)` to update the polymorphic relationship on the token groups table~
- [x] Added a warning using deface with a link on how to modify this setting
- [x] Tests
